server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0

spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://localhost:8088"
  cloud:
    gateway:
      routes:
        - id: employee-service
          uri: lb://employee-service
          predicates:
            - Path=/employee/**
        - id: department-service
          uri: lb://department-service
          predicates:
            - Path=/department/**
        - id: api-server
          uri: lb://api-server
          predicates:
            - Path=/api-server/**
        - id: api-server
          uri: lb://api-server
          predicates:
            - Path=/api/v1/**
        - id: api-server
          uri: lb://api-server
          predicates:
            - Path=/apiserver/**
        - id: be-service
          uri: lb://be-service
          predicates:
            - Path=/be/**
