server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0

spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://localhost:8088"
  cloud:
    gateway:
      routes:
        - id: api-service-1
          uri: lb://api-service
          predicates:
            - Path=/api/**
        - id: api-service-2
          uri: lb://api-service
          predicates:
            - Path=/actuator/**
            - Path=/v3/api-docs
            - Path=/v3/api-docs/**
            - Path=/swagger-ui.html
        - id: background-service-1
          uri: lb://background-service
          predicates:
            - Path=/background-service/**
        - id: bg-service-1
          uri: lb://bg-service
          predicates:
            - Path=/bg-service/**
        - id: email-service-1
          uri: lb://email-service
          predicates:
            - Path=/email-service/**