version: "3.8"

services:
  mongodb:
    container_name: "mongodb_container_local"
    image: mongo:latest
    hostname: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - spring

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin_container_local
    ports:
      - 9411:9411
    networks:
      - spring
#  localstack:
#    container_name: "localstack_container_local}"
#    image: localstack/localstack
#    environment:
#      - DEBUG=${DEBUG-}
#      - DOCKER_HOST=unix:///var/run/docker.sock
#    ports:
#      - "127.0.0.1:4566:4566"            # LocalStack Gateway
#      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
#    volumes:
#      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
#      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  mongodb_data_container:

networks:
  spring:
    driver: bridge